// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABEGwDud67PdI-59ALRjKHkQoAbJ6nC1g',
    appId: '1:217175879702:web:e1553841d16fce15530537',
    messagingSenderId: '217175879702',
    projectId: 'green-learning-416d6',
    authDomain: 'green-learning-416d6.firebaseapp.com',
    storageBucket: 'green-learning-416d6.appspot.com',
    measurementId: 'G-12XLLZLK79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQktFOJs6W0tMoQG7DFCsapqiMXgF-J4',
    appId: '1:217175879702:android:e33fbadd3f02de45530537',
    messagingSenderId: '217175879702',
    projectId: 'green-learning-416d6',
    storageBucket: 'green-learning-416d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGE7_N1Q83tAxzci7OpevfGy1-CCHx7-Y',
    appId: '1:217175879702:ios:d42141f3f14b68a9530537',
    messagingSenderId: '217175879702',
    projectId: 'green-learning-416d6',
    storageBucket: 'green-learning-416d6.appspot.com',
    iosBundleId: 'com.impossibleshadowstorm.greenLearning',
  );
}
