// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFmTqgljIWvFJaR1JCSCko7ZkxqQyNHZE',
    appId: '1:358517457426:web:16415c7de8e04ceb760ecb',
    messagingSenderId: '358517457426',
    projectId: 'uniford-firebase-c4605',
    authDomain: 'uniford-firebase-c4605.firebaseapp.com',
    storageBucket: 'uniford-firebase-c4605.appspot.com',
    measurementId: 'G-WJQQ2Y0SKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD6YzGz6Oqf5T5vFYT5aRkiHYpFqTP5GM',
    appId: '1:358517457426:android:633284614220688a760ecb',
    messagingSenderId: '358517457426',
    projectId: 'uniford-firebase-c4605',
    storageBucket: 'uniford-firebase-c4605.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxbCXbUpCs9u8qgs4jrwl8133i3Bb-pfo',
    appId: '1:358517457426:ios:bbf38a46711312cc760ecb',
    messagingSenderId: '358517457426',
    projectId: 'uniford-firebase-c4605',
    storageBucket: 'uniford-firebase-c4605.appspot.com',
    iosBundleId: 'com.impossibleshadowstorm.greenLearning',
  );
}
